services:
  postgres:
    image: postgres:16-alpine
    container_name: kharchapay-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kharchapay
    ports:
      - "5432:5432"
    volumes:
      - kharchapay_pgdata:/var/lib/postgresql/data

volumes:
  kharchapay_pgdata:
