import type { TourId, TourDefinition } from "./types";

export const TOURS: Record<TourId, TourDefinition> = {
  /**
   * ADMIN — full platform walkthrough covering every feature admins control:
   * dashboard, team, requests, approvals, payments, vendors, procurement,
   * reports, governance, settings, treasury, integrations, and more.
   */
  dashboard_admin: {
    id: "dashboard_admin",
    title: "KharchaPay Admin Tour",
    description: "A complete walkthrough of your admin capabilities — from dashboards and spending to treasury, compliance, and integrations.",
    rolesAllowed: ["ADMIN"],
    autoStart: true,
    steps: [
      {
        id: "admin-welcome",
        target: "dashboard.header",
        title: "Welcome to KharchaPay, Admin!",
        body: "As an Admin, you have full control over your organization's finances — budgets, approvals, payments, vendor management, treasury operations, and more. Let's walk through every feature available to you.",
        placement: "bottom",
        route: "/app/dashboard",
      },
      {
        id: "admin-kpis",
        target: "dashboard.kpis",
        title: "Key Performance Indicators",
        body: "These KPI cards give you a real-time financial snapshot: total budget, approved spend, payments made, remaining balance, burn rate, and runway. The color-coded borders flag healthy (green), warning (amber), or critical (red) metrics.",
        placement: "bottom",
        skipIfMissing: true,
      },
      {
        id: "admin-setup-checklist",
        target: "dashboard.setup-checklist",
        title: "Setup Checklist",
        body: "When you first create an org, this checklist guides you through initial setup — adding departments, budgets, GL codes, vendors, and connecting integrations. Complete all items to get the most out of KharchaPay.",
        placement: "bottom",
        skipIfMissing: true,
      },
      {
        id: "admin-notifications",
        target: "header.notifications",
        title: "Notifications",
        body: "The bell icon shows real-time alerts for pending approvals, completed payments, policy violations, vendor changes, and treasury events. Badges indicate unread count so nothing slips through.",
        placement: "bottom",
        align: "end",
      },
      {
        id: "admin-theme-toggle",
        target: "header.theme-toggle",
        title: "Dark Mode",
        body: "Toggle between light and dark mode. Your preference is saved automatically.",
        placement: "bottom",
        skipIfMissing: true,
      },
      {
        id: "admin-user-menu",
        target: "header.user-menu",
        title: "Your Account & Settings",
        body: "Access your profile, upload an avatar, switch organizations, use \"View as Role\" to preview what other roles see, reset product tours, or log out.",
        placement: "bottom",
        align: "end",
      },
      // ── Sidebar: Work section ──
      {
        id: "admin-chat",
        target: "sidebar.chat",
        title: "Team Chat",
        body: "Built-in team messaging with channels, threads, file attachments, pinned messages, and full-text search. Chat uses real-time SSE streaming so your team stays in sync without leaving the app.",
        placement: "right",
      },
      {
        id: "admin-new-request",
        target: "sidebar.new-request",
        title: "Create Spending Requests",
        body: "Start a new spending request here. Specify the amount, category, department, vendor, and justification. Requests go through your approval policy before payment.",
        placement: "right",
      },
      {
        id: "admin-requests",
        target: "sidebar.requests",
        title: "All Requests",
        body: "View every spending request across your org — filter by status (Draft, Pending, Approved, Rejected, Paid), department, requester, or date. Click any request for full details, approval history, and receipt attachments.",
        placement: "right",
      },
      {
        id: "admin-approvals",
        target: "sidebar.approvals",
        title: "Approval Queue",
        body: "Your central approval queue. The badge shows pending requests. KharchaPay enforces Separation of Duties — requesters can't approve their own requests. Multi-tier approval policies can require multiple approvers for high-value items.",
        placement: "right",
      },
      {
        id: "admin-payments",
        target: "sidebar.payments",
        title: "Payments",
        body: "Track all disbursements. Approved requests appear here for payment processing. Payments are executed on-chain via Solana Token-2022 with Required Memo for auditability, or via Circle fiat off-ramping to vendor bank accounts.",
        placement: "right",
      },
      {
        id: "admin-vendors",
        target: "sidebar.vendors",
        title: "Vendor Management",
        body: "Full vendor lifecycle management — from onboarding to payment. Each vendor has a 360° view showing contacts, documents (W9, contracts), payment methods, bank change requests with dual-approval, risk levels, and payout profiles for fiat off-ramping.",
        placement: "right",
      },
      {
        id: "admin-purchase-orders",
        target: "sidebar.purchase-orders",
        title: "Purchase Orders (POs)",
        body: "Create and manage purchase orders with line items. POs flow through Draft → Issued → Partially Received → Received → Closed. POs link to invoices for 2-way and 3-way matching (PO ↔ Invoice ↔ Goods Receipt).",
        placement: "right",
      },
      {
        id: "admin-receipts",
        target: "sidebar.receipts",
        title: "Receipts",
        body: "Upload and manage receipts (PDF, JPEG, PNG, WebP). Your Spend Policy can require receipts before payment, optionally above a certain amount threshold. Receipts are stored securely outside the public directory with magic-byte validation.",
        placement: "right",
      },
      {
        id: "admin-invoices",
        target: "sidebar.invoices",
        title: "Invoices",
        body: "Full invoice management — create, submit, verify, approve, and pay. Supports GL coding, attachments, bulk assignment, bulk verification, and PO/GRN matching with configurable tolerances. Invoices flow: Draft → Submitted → Verified → Approved.",
        placement: "right",
      },
      // ── Sidebar: Insights ──
      {
        id: "admin-reports",
        target: "sidebar.reports",
        title: "Reports & Exports",
        body: "Generate reports on spending trends, budget vs. actual, department breakdowns, and payment history. Export to CSV for requests, payments, budget reports, and audit logs.",
        placement: "right",
      },
      // ── Sidebar: Governance ──
      {
        id: "admin-audit-log",
        target: "sidebar.audit-log",
        title: "Audit Log",
        body: "An append-only audit trail of every action in your org — request creation, approvals, rejections, payments, vendor changes, policy updates, and more. Retention is configurable (30 to 3,650 days). Treasury operations have a separate immutable audit log.",
        placement: "right",
      },
      {
        id: "admin-compliance",
        target: "sidebar.compliance",
        title: "Compliance Dashboard",
        body: "Monitor compliance posture — policy violations, missing receipts, overdue approvals, and security checks. Useful for regulatory audits and internal controls review.",
        placement: "right",
      },
      // ── Sidebar: Settings ──
      {
        id: "admin-setup",
        target: "sidebar.setup",
        title: "Setup & Quick Start",
        body: "One-page setup wizard to configure your org — add departments, set budgets, create GL codes, invite team members, and connect integrations. Come here first when setting up a new organization.",
        placement: "right",
      },
      {
        id: "admin-members",
        target: "sidebar.members",
        title: "Team Members",
        body: "Invite team members and assign roles: Admin (full control), Approver (review + approve), Staff (submit requests), or Auditor (read-only view). Each role has precise permissions — the RBAC system ensures users only see and do what they should.",
        placement: "right",
      },
      {
        id: "admin-docs",
        target: "sidebar.docs",
        title: "Documentation",
        body: "In-app documentation covering workflows, policies, blockchain integration, and API reference. Share with your team so everyone understands how KharchaPay works.",
        placement: "right",
      },
      {
        id: "admin-finish",
        target: "dashboard.header",
        title: "You're All Set!",
        body: "That's the full admin tour. You also have access to Departments, Budgets, Approval Policy, Spend Policy, GL Codes, Audit Retention, Matching & Controls, and Integrations (QuickBooks) in the Settings section. Explore at your own pace — you can always reset this tour from the user menu.",
        placement: "bottom",
        route: "/app/dashboard",
      },
    ],
  },

  /**
   * STAFF — covers everything a staff member can do:
   * submit requests, track payments, procurement, receipts, invoices, chat.
   */
  create_request_staff: {
    id: "create_request_staff",
    title: "KharchaPay Staff Tour",
    description: "Learn every feature available to you as a Staff member — from submitting spending requests to tracking payments, managing procurement, and collaborating with your team.",
    rolesAllowed: ["STAFF", "APPROVER", "ADMIN"],
    autoStart: true,
    steps: [
      {
        id: "staff-welcome",
        target: "dashboard.header",
        title: "Welcome to KharchaPay!",
        body: "As a Staff member, you can submit spending requests, create purchase orders, upload receipts, manage invoices, and communicate with your team. Let's walk through everything you can do.",
        placement: "bottom",
        route: "/app/dashboard",
      },
      {
        id: "staff-dashboard",
        target: "dashboard.kpis",
        title: "Your Dashboard",
        body: "Your dashboard shows your recent requests and their statuses. Track how much has been spent across departments and see where your requests stand in the approval pipeline.",
        placement: "bottom",
        skipIfMissing: true,
      },
      {
        id: "staff-notifications",
        target: "header.notifications",
        title: "Stay in the Loop",
        body: "You'll get notifications when your requests are approved, rejected, or paid. The badge count tells you how many unread notifications are waiting.",
        placement: "bottom",
        align: "end",
      },
      {
        id: "staff-chat",
        target: "sidebar.chat",
        title: "Team Chat",
        body: "Collaborate with your team without leaving KharchaPay. Send messages in channels, share files, reply in threads, pin important messages, and search conversation history.",
        placement: "right",
      },
      {
        id: "staff-new-request",
        target: "sidebar.new-request",
        title: "Create a Spending Request",
        body: "This is where most of your work begins. Click \"New request\" to submit a spending request. You'll fill in the amount, select a department, choose a vendor, pick a category, and explain the purpose. Once submitted, it goes to your org's approval chain.",
        placement: "right",
      },
      {
        id: "staff-requests-list",
        target: "sidebar.requests",
        title: "Track Your Requests",
        body: "See all your submitted requests and their current status: Draft (not yet submitted), Pending (waiting for approval), Approved (ready for payment), Rejected, or Paid. Filter and search to find specific requests quickly.",
        placement: "right",
      },
      {
        id: "staff-payments",
        target: "sidebar.payments",
        title: "Payment Tracking",
        body: "Once an admin processes payment for your approved request, the details appear here — including transaction signature, payment method, and timestamp. Payments are made via on-chain Solana Token-2022 transfers or fiat bank disbursements.",
        placement: "right",
      },
      {
        id: "staff-vendors",
        target: "sidebar.vendors",
        title: "Vendor Directory",
        body: "Browse the vendor directory to find approved vendors when creating requests. You can view vendor details, contacts, and status. Only vendors with \"Active\" status can be used in spending requests.",
        placement: "right",
      },
      {
        id: "staff-purchase-orders",
        target: "sidebar.purchase-orders",
        title: "Purchase Orders",
        body: "Create purchase orders (POs) for planned purchases. Add line items with quantities and unit prices. POs provide a paper trail and link to invoices for automated matching.",
        placement: "right",
      },
      {
        id: "staff-receipts",
        target: "sidebar.receipts",
        title: "Upload Receipts",
        body: "Attach receipts to your requests — PDFs, images (JPEG, PNG, WebP). Your org's spend policy may require receipts before payment can be processed, especially for amounts above a set threshold.",
        placement: "right",
      },
      {
        id: "staff-invoices",
        target: "sidebar.invoices",
        title: "Invoice Management",
        body: "Create and submit invoices for verification. Invoices can be linked to POs for automated 2-way or 3-way matching. Add GL codes, attach supporting documents, and track the invoice through its lifecycle.",
        placement: "right",
      },
      {
        id: "staff-reports",
        target: "sidebar.reports",
        title: "Reports",
        body: "View spending reports and trends across departments. Export data as CSV for your own records. Reports help you understand where money is going and plan future requests.",
        placement: "right",
      },
      {
        id: "staff-setup",
        target: "sidebar.setup",
        title: "Setup & Preferences",
        body: "View your org setup and configuration. As a staff member, you can see the organizational structure but admin-only settings will be read-only.",
        placement: "right",
      },
      {
        id: "staff-docs",
        target: "sidebar.docs",
        title: "Documentation",
        body: "Find detailed guides on how to use KharchaPay — creating requests, uploading receipts, understanding approval workflows, and more.",
        placement: "right",
      },
      {
        id: "staff-user-menu",
        target: "header.user-menu",
        title: "Your Account",
        body: "Access your profile, update your avatar, and manage your account settings. You can also reset this product tour anytime from the user menu. That's the full tour — you're ready to start submitting requests!",
        placement: "bottom",
        align: "end",
      },
    ],
  },

  /**
   * APPROVER — covers approvals workflow, request review, vendor oversight,
   * procurement, reports, and everything an approver needs.
   */
  approvals_approver: {
    id: "approvals_approver",
    title: "KharchaPay Approver Tour",
    description: "Master your approval workflow — review requests, manage vendors, track payments, and use reports to make informed decisions.",
    rolesAllowed: ["APPROVER", "ADMIN"],
    autoStart: true,
    steps: [
      {
        id: "approver-welcome",
        target: "dashboard.header",
        title: "Welcome, Approver!",
        body: "As an Approver, you're a key gatekeeper for your org's spending. You'll review and approve/reject spending requests, oversee vendor onboarding, verify invoices, and monitor financial reports. Let's explore your full toolkit.",
        placement: "bottom",
        route: "/app/dashboard",
      },
      {
        id: "approver-kpis",
        target: "dashboard.kpis",
        title: "Dashboard Metrics",
        body: "Your dashboard highlights spending activity — budget utilization, pending approvals count, payment status, and attention items. Use the time range picker to analyze different periods.",
        placement: "bottom",
        skipIfMissing: true,
      },
      {
        id: "approver-notifications",
        target: "header.notifications",
        title: "Approval Notifications",
        body: "You'll receive notifications whenever a new request needs your approval, when a payment is processed, or when vendor changes require review. Badge count shows unread items.",
        placement: "bottom",
        align: "end",
      },
      {
        id: "approver-chat",
        target: "sidebar.chat",
        title: "Team Chat",
        body: "Communicate with requesters and admins directly. If you need clarification on a request before approving, discuss it in the team chat. Channels, threads, attachments, and search are all available.",
        placement: "right",
      },
      {
        id: "approver-approvals",
        target: "sidebar.approvals",
        title: "Approval Queue — Your Primary Workspace",
        body: "This is your most important page. The badge shows how many requests are waiting for your review. Open each request to see the amount, purpose, department, vendor, and attached receipts. Approve or reject with an optional note. Separation of Duties prevents you from approving your own requests.",
        placement: "right",
      },
      {
        id: "approver-new-request",
        target: "sidebar.new-request",
        title: "Submit Your Own Requests",
        body: "You can also submit spending requests. Your requests will go through the same approval chain — another approver or admin will review them (you can't approve your own).",
        placement: "right",
      },
      {
        id: "approver-requests",
        target: "sidebar.requests",
        title: "All Requests",
        body: "Browse all requests across the org, including ones you've already acted on. Filter by status, department, or requester to find specific items. Click any request for its full approval history and timeline.",
        placement: "right",
      },
      {
        id: "approver-payments",
        target: "sidebar.payments",
        title: "Payment Tracking",
        body: "After you approve a request, the admin processes payment. Track payment status here — see which approved requests have been paid, payment method (on-chain or fiat), and transaction details.",
        placement: "right",
      },
      {
        id: "approver-vendors",
        target: "sidebar.vendors",
        title: "Vendor Oversight",
        body: "Review vendor profiles, documents, and onboarding status. As an approver, you can flag vendors as \"Blocked\" if there are compliance concerns. You may also participate in bank change request approvals depending on your org's vendor policy.",
        placement: "right",
      },
      {
        id: "approver-purchase-orders",
        target: "sidebar.purchase-orders",
        title: "Purchase Orders",
        body: "View and create purchase orders. POs document planned purchases and link to invoices for automated matching. Check PO line items against what was actually received and invoiced.",
        placement: "right",
      },
      {
        id: "approver-receipts",
        target: "sidebar.receipts",
        title: "Receipts",
        body: "View and upload receipts attached to requests and invoices. The spend policy may require receipts before approvals or payments can proceed.",
        placement: "right",
      },
      {
        id: "approver-invoices",
        target: "sidebar.invoices",
        title: "Invoice Verification",
        body: "Review and verify invoices. Invoices go through DRAFT → SUBMITTED → NEEDS_VERIFICATION → VERIFIED → APPROVED. You can verify invoices, check PO/GRN matching results, and flag exceptions. Bulk verify and bulk assign are available for efficiency.",
        placement: "right",
      },
      {
        id: "approver-reports",
        target: "sidebar.reports",
        title: "Spending Reports",
        body: "Analyze spending trends before approving large requests. View department breakdowns, budget vs. actual, and payment history. Export reports to CSV for offline review. Make data-driven approval decisions.",
        placement: "right",
      },
      {
        id: "approver-setup",
        target: "sidebar.setup",
        title: "Setup",
        body: "View your organization's configuration — departments, vendors, and general settings.",
        placement: "right",
      },
      {
        id: "approver-docs",
        target: "sidebar.docs",
        title: "Documentation",
        body: "Detailed guides on approval workflows, spend policies, vendor management, and procurement processes.",
        placement: "right",
      },
      {
        id: "approver-finish",
        target: "header.user-menu",
        title: "You're Ready!",
        body: "That's your complete approver toolkit. Your primary workflow: check the Approval Queue, review requests, approve or reject with notes, and monitor reports for trends. You can reset this tour anytime from the user menu. Happy reviewing!",
        placement: "bottom",
        align: "end",
      },
    ],
  },

  /**
   * AUDITOR — read-only tour covering every audit and compliance tool:
   * dashboard, requests, payments, procurement, reports, audit log,
   * compliance. Emphasizes that all access is read-only.
   */
  audit_auditor: {
    id: "audit_auditor",
    title: "KharchaPay Auditor Tour",
    description: "Navigate the complete audit and compliance toolkit — read-only access to all financial data, audit logs, compliance dashboards, and exportable reports.",
    rolesAllowed: ["AUDITOR"],
    autoStart: true,
    steps: [
      {
        id: "auditor-welcome",
        target: "dashboard.header",
        title: "Welcome, Auditor!",
        body: "As an Auditor, you have read-only access to all financial data in the organization. You can view every request, payment, vendor, PO, invoice, receipt, and report — but you cannot create, modify, or approve anything. This ensures audit independence. Let's explore your tools.",
        placement: "bottom",
        route: "/app/dashboard",
      },
      {
        id: "auditor-kpis",
        target: "dashboard.kpis",
        title: "Financial Overview",
        body: "The dashboard KPIs give you a high-level view: total budget, approved vs. paid spend, remaining balance, burn rate, and runway. Use the time range picker to examine different periods for your audit scope.",
        placement: "bottom",
        skipIfMissing: true,
      },
      {
        id: "auditor-notifications",
        target: "header.notifications",
        title: "Audit Notifications",
        body: "You receive notifications about significant events — completed payments, policy changes, and compliance flags. Stay informed without needing to actively monitor every page.",
        placement: "bottom",
        align: "end",
      },
      {
        id: "auditor-chat",
        target: "sidebar.chat",
        title: "Team Chat (Read-Only)",
        body: "You can view team chat channels and message history. This is useful for investigating communication around specific transactions or approvals.",
        placement: "right",
      },
      {
        id: "auditor-requests",
        target: "sidebar.requests",
        title: "Spending Requests",
        body: "Browse every spending request in the organization. View request details, amounts, departments, vendors, approval history (who approved/rejected and when), attached receipts, and payment status. Filter by any criteria to focus your audit.",
        placement: "right",
      },
      {
        id: "auditor-payments",
        target: "sidebar.payments",
        title: "Payment Records",
        body: "View all payment records with full details — amounts, methods, transaction signatures, timestamps, and on-chain verification status. Payments include both Solana Token-2022 on-chain transfers and Circle fiat off-ramp disbursements.",
        placement: "right",
      },
      {
        id: "auditor-vendors",
        target: "sidebar.vendors",
        title: "Vendor Records",
        body: "Access the full vendor directory with 360° views — contacts, uploaded documents (W9, contracts, insurance), payment methods, bank change request history, onboarding cases, risk levels, and transaction history with each vendor.",
        placement: "right",
        skipIfMissing: true,
      },
      {
        id: "auditor-purchase-orders",
        target: "sidebar.purchase-orders",
        title: "Purchase Orders",
        body: "Review all purchase orders with line items, status progression, linked goods receipts, and matching results. Verify that the procure-to-pay chain (PO → GRN → Invoice → Payment) is complete and consistent.",
        placement: "right",
      },
      {
        id: "auditor-receipts",
        target: "sidebar.receipts",
        title: "Receipt Archive",
        body: "View and download all uploaded receipts. Verify that required receipts are attached to spending requests and invoices. Receipts are stored securely with magic-byte validation to prevent file type spoofing.",
        placement: "right",
      },
      {
        id: "auditor-invoices",
        target: "sidebar.invoices",
        title: "Invoice Records",
        body: "Review all invoices with full detail — line items, GL coding, PO/GRN matching results (2-way and 3-way), attachments, verification history, and status progression. Identify exceptions and mismatches.",
        placement: "right",
      },
      {
        id: "auditor-reports",
        target: "sidebar.reports",
        title: "Reports & Exports",
        body: "Generate and export comprehensive reports: spending by department, budget vs. actual, payment history, and custom date ranges. Export to CSV for use in your audit workpapers.",
        placement: "right",
      },
      {
        id: "auditor-audit-log",
        target: "sidebar.audit-log",
        title: "Audit Log — Your Primary Tool",
        body: "The append-only audit log records every action in the system with timestamps and actor IDs: request creation, submissions, approvals, rejections, payments, vendor changes, policy updates, and more. Treasury operations have a separate immutable ledger that cannot be edited or deleted even by admins.",
        placement: "right",
      },
      {
        id: "auditor-compliance",
        target: "sidebar.compliance",
        title: "Compliance Dashboard",
        body: "Monitor compliance posture across the organization — policy violations, missing receipts, overdue approvals, security check results, and control effectiveness. Generate compliance reports for regulatory submissions.",
        placement: "right",
      },
      {
        id: "auditor-docs",
        target: "sidebar.docs",
        title: "Documentation",
        body: "Reference documentation covering workflows, data models, policy configurations, blockchain integration details, and API structure. Useful for understanding the system during your audit.",
        placement: "right",
      },
      {
        id: "auditor-finish",
        target: "header.user-menu",
        title: "You're All Set!",
        body: "That's your complete auditor toolkit. Remember: you have full visibility but no write access — this ensures audit independence. Focus on the Audit Log and Compliance Dashboard for governance reviews. You can reset this tour anytime from the user menu.",
        placement: "bottom",
        align: "end",
      },
    ],
  },
};

export function getTourById(id: TourId): TourDefinition | undefined {
  return TOURS[id];
}

export const ALL_TOUR_IDS = Object.keys(TOURS) as TourId[];
